In [12]:
import numpy as np
integers=np.array([10,20,30,40,50])
print (integers)
integers[0]=20
integers
integers.dtype
smallerintegers=np.array(integers,dtype=np.int8)
smallerintegers
integers.nbytes
smallerintegers.nbytes
integers.nbytes
floats=np.array([1.2,2.3,3.4,5.1,8.3])
print (floats)
floats.dtype

[10 20 30 40 50]
[1.2 2.3 3.4 5.1 8.3]


dtype('float64')

In [27]:
import numpy as np
nums=np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums
nums[0,0]
nums[1,4]
nums.ndim
multi_array=np.array([[[1,2,3],[6,7,8]],
            [[11,12,13],[16,17,18]]])
multi_array
multi_array[1,1,2]

18

In [38]:
import numpy as np
first_list=[1,2,3,4,5,6,7,8,9,10]
first_list
first_array=np.array(first_list)
first_array
second_list=[1,2,3,-1,23,50,128000.56,4.56]
second_array=np.array(second_list)
second_array
second_array.dtype
third_list=['ann',111111,'peter',111112,'susan',111113,'john',111114]
third_array=np.array(third_list)
third_array
first_tuple=(5,10,15,20,25,30)
array_from_tuple=np.array(first_tuple)
array_from_tuple
array_from_tuple.dtype
multi_dim_list=([[[1,2,3],[6,7,8]],
            [[11,12,13],[16,17,18]]])
multi_dim_list
arr_from_multi_dim_list=np.array(multi_dim_list)
arr_from_multi_dim_list




array([[[ 1,  2,  3],
        [ 6,  7,  8]],

       [[11, 12, 13],
        [16, 17, 18]]])

In [49]:
import numpy as np
integers_array=np.arange(10)
integers_array
integers_second_array=np.arange(100,130)
integers_second_array
integers_third_array=np.arange(100,151,2)
integers_third_array
first_floats_arr=np.linspace(10,20)
first_floats_arr
second_floats_arr=np.linspace(10,20,5)
second_floats_arr
integers_third_array
first_rand_arr=np.random.rand(10)
first_rand_arr
second_rand_arr=np.random.rand(4,4)
second_rand_arr
third_rand_arr=np.random.randint(0,100,20)
third_rand_arr

array([83, 18, 19, 79, 51, 64, 23, 35,  5, 81, 33, 42, 84, 58, 86, 14, 17,
       94, 85, 31])

In [61]:
import numpy as np
first_z_array=np.zeros(5)
first_z_array
second_z_array=np.zeros((4,5))
second_z_array
third_z_array=np.zeros(((5,5,5)))
third_z_array
third_ones_array=np.ones((4,5),dtype=int)
third_ones_array
first_fill_array=np.empty(10,dtype=int)
first_fill_array.fill(12)
first_fill_array
first_full_array=np.full(5,10)
first_full_array
second_full_array=np.full((4,5),8)
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [69]:
import numpy as np
first_arr=np.arange(20)
first_arr
second_arr=np.linspace((1,2),(10,20),10)
second_arr
third_arr=np.full((2,2,2),10)
third_arr
np.shape(first_arr)
second_arr
np.shape(second_arr)
third_arr


array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [82]:
second_arr=np.array([1,2,3,4])
second_arr
new_second_arr=np.append(second_arr,5)
new_second_arr
third_arr=np.array([1,2,3,4,5])
third_arr
del_arr=np.delete(third_arr,4)
del_arr
integers_arr=np.random.randint(0,20,20)
integers_arr
print(np.sort(integers_arr))
integers_2dim_arr=np.array([[3,2,5,7,4],[5,0,8,3,1]])
integers_2dim_arr
print(np.sort(integers_2dim_arr))
colors=np.array(['orange','green','yellow','white','black','pink'])
colors
print(np.sort(colors))

[ 0  0  1  1  1  4  6  6  7  7  9  9  9 10 10 11 14 16 17 19]
[[2 3 4 5 7]
 [0 1 3 5 8]]
['black' 'green' 'orange' 'pink' 'white' 'yellow']


In [ ]:
import numpy as np
students_ids_number=([1111,1212,1313,1414,1515,1616,1717,1818])
students_ids_number
students_ids_number_reg=students_ids_number
print('id of students ids number',id(students_ids_number))
print('id of students ids number reg',id(students_ids_number_reg))
students_ids_number_cp=students_ids_number.copy()
print(students_ids_number.cp)
print('id of students ids number',id(students_ids_number))
print('id of students ids number',id(students_ids_number_cp))





id of students ids number 2515941762176
id of students ids number reg 2515941762176
